  #PBS    -N  B3
  #PBS    -o  /ghome/arm2010/Baseline_a3/$PBS_JOBID.out
  #PBS    -e  /ghome/arm2010/Baseline_a3/$PBS_JOBID.err
  #PBS    -l nodes=1:gpus=1:G
  #PBS    -l walltime=300:00:00
  #PBS    -r y
  cd $PBS_O_WORKDIR
  echo Time is `date`
  echo Directory is $PWD
  echo This job runs on following nodes:
  echo -n "Node:"
  cat $PBS_NODEFILE
  echo -n "Gpus:"
  cat $PBS_GPUFILE
  echo "CUDA_VISIBLE_DEVICES:"$CUDA_VISIBLE_DEVICES
  startdocker -D /gdata/arm2010 -P /ghome/arm2010/Baseline_a3/ -c "python /ghome/arm2010/Baseline_a3/train.py"  bit:5000/amr_issp_2

